// FrontEndAngular/src/app/Components/folder-item/folder-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { faTrash } from '@fortawesome/free-solid-svg-icons';
import { Folder } from 'src/app/config/interfaces';
import { FoldersApiService } from 'src/app/config/folders-api.service';
import { FolderService } from 'src/app/config/folder.service';

@Component({
  selector: 'app-folder-item',
  templateUrl: './folder-item.component.html',
  styleUrls: ['./folder-item.component.scss']
})
export class FolderItemComponent implements OnInit {

  faTrash = faTrash
  @Input() folder!: Folder
  notDeleted: Boolean = true

  constructor(private foldersApiService: FoldersApiService,
     private folderService: FolderService) { }

  deleteFolder() {
    this.foldersApiService.deleteFolder(this.folder.id)
    this.notDeleted = false;
  }

  setFolderInService() {
    this.folderService.setFolder(this.folder)
  }

  ngOnInit(): void {
  }

}

<div *ngIf="notDeleted" class="folder-format folder-change-color">
  <div class="folder-format--center-vertically">
    <label class="folder-label-format"> {{folder.title}} </label>
    <fa-icon
      [icon]="faTrash"
      (click) = "deleteFolder()"
      class="folder-erase-format"
      title="Delete Folder (this operation will delete all items inside the folder)"
    ></fa-icon>
    <a (click) = "setFolderInService()"[routerLink]="['/toDos/folders',folder.id]">
      <label class="folder-view-items-label"> View Items </label>
    </a>
  </div>
</div>

// FrontEndReactJS/src/Components/FolderItem/FolderItem.jsx
import { Link } from "react-router-dom";
import "./FolderItem.scss";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faTrash } from "@fortawesome/free-solid-svg-icons";

function FolderItem(props) {
  const folder = props.folder;

  const deleteFolderItem = () => {
    props.deleteFolder(folder.id)
  };

  if (folder !== undefined)
    return (
      <div className="folder-format folder-change-color">
        <div className="folder-format--center-vertically">
          <label className="folder-label-format">{folder.title}</label>
          <FontAwesomeIcon
            icon={faTrash}
            className="folder-erase-format"
            onClick={deleteFolderItem}
            title="Delete Folder (this operation will delete all items inside the folder)"
          />
          <Link
            to={`/toDos/folders/${folder.title}`}
            state={{ folder: folder }}
          >
            <label className="folder-view-items-label"> View Items </label>
          </Link>
        </div>
      </div>
    );
  else return null;
}

export default FolderItem;
