// FrontEndAngular/src/app/Screens/folders-list/folders-list.component.ts
import { Component, OnInit } from '@angular/core';
import { throwError } from 'rxjs';
import { FoldersApiService } from '../../config/folders-api.service';
import { LoginService } from 'src/app/config/login.service';
import { Folder, FolderToAdd, Response } from '../../config/interfaces';


@Component({
  selector: 'app-folders-list',
  templateUrl: './folders-list.component.html',
  styleUrls: ['./folders-list.component.scss']
})
export class FoldersListComponent implements OnInit {

  constructor(private foldersApiService: FoldersApiService,
    private loginService: LoginService ) {
      this.loginService.isLoggedIn.subscribe(logged => this.changeLoggedIn(logged))
  }

  folders: Folder[] | undefined;
  newFolder: FolderToAdd = { title: "" };
  errorMessage: string = "";
  isLoggedIn: boolean = false;


  async createFolder() {
    try {
      this.newFolder.title = this.newFolder.title.trim()
      let response: Response = await this.foldersApiService.createFolder(this.newFolder)
      if (response.status === "Error") throw response.message
      this.folders?.push(response.data)
    }
    catch (error: any) {
      this.errorMessage = error
    }
    finally {
      this.newFolder = { title: "" }
    }
  }

  async getFolders() {
    let response: Response = await this.foldersApiService.getFolders()
    if (response.status === "Error") {
      //Revisar porque no catchea el error la funcion padre
      console.log("Error")
      throw ("Error retrieving Folders")
    }
    this.folders = response.data;
    console.log(this.folders)
  }

  private changeLoggedIn(isLoggedIn : boolean): void{
    this.isLoggedIn = isLoggedIn;
  }


  ngOnInit(): void {
    try {
      this.getFolders();
      this.loginService.getIsLoggedIn();
    } catch (error: any) {
      this.errorMessage = error
    }
  }
}

<div *ngIf="isLoggedIn; else notLogged" class="folder-list-format">
  <label class="title-format">To-Do List</label>
  <br />
  <div class="sub-title-container">
    <label class="sub-title-format"> Folders </label>
  </div>
  <div class="folder-list__items-container">
    <app-folder-item
      *ngFor="let folder of folders"
      [folder]="folder"
    ></app-folder-item>
  </div>
  <div class="folder-list__buttons">
    <form class="folder-list__add">
      <input
        type="text"
        class="input-format"
        [(ngModel)]="newFolder.title"
        name="folderTitle"
        placeholder="Insert new Folder's Title"
      />
      <button
        (click)="createFolder()"
        class="button-format folder-list__add__button"
      >
        <label>Create folder</label>
      </button>
    </form>
    <div class="error-message-container">
      <label class="error-message-label">{{ errorMessage }}</label>
    </div>
  </div>
</div>
<ng-template #notLogged>
  <div class="folder-list-format">
    <label class="not-logged-label"> You have to login first </label>
  </div>
</ng-template>

// FrontEnd/src/Screens/Folders_List/Folders_List.jsx
import { useState, useEffect } from "react";
import { getAllFolders, addFolder, deleteFolder } from "../../Api/FolderApi";
import FolderItem from "../../Components/FolderItem/FolderItem";
import "./Folders_List.scss";

function Folder_List(props) {
  const [errorMessage, setErrorMessage] = useState("");
  const [folderList, setFolderList] = useState([]);
  const [newFolder, setNewFolder] = useState({
    title: "",
  });

  const addNewFolderToDatabase = async () => {
    addFolder(newFolder).then((response) => {
      setFolderList([...folderList, response.data]);
    });
  };

  const deleteFolderFromDatabase = async (id) => {
    deleteFolder(id).then((response) => {
      setFolderList(folderList.filter((folder) => folder.id !== id));
    });
  };

  const getFoldersFromDatabase = async () => {
    try {
      getAllFolders().then((response) => {
        setFolderList(response.data);
      });
    } catch (e) {
      console.log("Error: ", e);
    }
  };

  const addNewFolderItem = (e) => {
    e.preventDefault();
    try {
      if (newFolder.title === "")
        throw new Error("The title field cannot be empty");
      const indexWithSameTitle = folderList
        .map((folder) => folder.title)
        .indexOf(newFolder.title);
      if (indexWithSameTitle !== -1)
        throw new Error("The is already a Folder with that title");
      addNewFolderToDatabase();
      setErrorMessage("");
    } catch (error) {
      setErrorMessage(error.message);
    } finally {
      setNewFolder({
        title: "",
        description: "",
        marked: false,
      });
    }
  };

  const handleChangeNewFolder = (e) => {
    const target = e.target;
    const value = target.value;
    if (value <= 255) {
      const name = target.name;

      setNewFolder({
        ...newFolder,
        [name]: value,
      });
    }
  };

  useEffect(() => {
    getFoldersFromDatabase();
  }, []);

  return (
    <div className="folder-list-format">
      {props.isLoggedIn ? (
        <>
          <label className="title-format">To-Do List</label>
          <br />
          <div className="sub-title-container">
            <label className="sub-title-format"> Folders </label>
          </div>{" "}
          <div className="folder-list__items-container">
            {folderList.map((folder) => {
              return (
                <FolderItem
                  folder={folder}
                  key={folder.id}
                  deleteFolder={deleteFolderFromDatabase}
                ></FolderItem>
              );
            })}
          </div>
          <div className="folder-list__buttons">
            <form onSubmit={addNewFolderItem} className="folder-list__add">
              <div>
                <input
                  type="text"
                  className="input-format"
                  name="title"
                  value={newFolder.title}
                  onChange={handleChangeNewFolder}
                  placeholder="Insert new Folder's Title"
                />
              </div>
              <button
                type="submit"
                className="button-format folder-list__add__button"
              >
                <label>Create folder</label>
              </button>
            </form>
            <div className="error-message-container">
              <label className="error-message-label">{errorMessage}</label>
            </div>
          </div>
        </>
      ) : (
        <label className="not-logged-label"> You have to login first </label>
      )}
    </div>
  );
}

export default Folder_List;
