// FrontEndAngular/src/app/Components/to-do-item/to-do-item.component.ts
import { Component, Input, OnInit, Output, EventEmitter } from '@angular/core';
import { faTimesCircle, faPen } from '@fortawesome/free-solid-svg-icons';
import { FolderService } from 'src/app/config/folder.service';
import { ToDos } from 'src/app/config/interfaces';
import { ToDoApiService } from 'src/app/config/to-do-api.service';
import { ToDosService } from 'src/app/config/to-dos.service';

@Component({
  selector: 'app-to-do-item',
  templateUrl: './to-do-item.component.html',
  styleUrls: ['./to-do-item.component.scss']
})
export class ToDoItemComponent implements OnInit {
  faTimesCircle = faTimesCircle;
  faPen = faPen;
  folderId: Number = NaN;
  notDeleted: Boolean = true;
  @Output() errorGenerated: EventEmitter<string> = new EventEmitter()
  @Input() toDo!: ToDos

  constructor(private folderService: FolderService,
    private toDoApiService: ToDoApiService,
    private toDoService: ToDosService) { }

  updateToDo() {
    this.toDoApiService.updateToDoMark(this.toDo.id,
      this.toDo.title,
      this.toDo.description,
      this.toDo.marked,
      this.folderId).then((response) => {
        if (response.status === 200) this.errorGenerated.emit("")
        if (response.status === 500) this.errorGenerated.emit("Error updating toDo")
      })
  }

  setToDoInService() {
    this.toDoService.setToDo(this.toDo);
  }
  deleteToDo() {
    this.toDoApiService.deleteToDo(this.toDo.id).then((response) => {
      if (response.status === 200) {
        this.notDeleted = false; this.errorGenerated.emit("")
      }
      if (response.status === 500) this.errorGenerated.emit("Error deleting the toDo")
    }, () => this.errorGenerated.emit("Error deleting the toDo"))
  }
  ngOnInit(): void {
    this.folderId = this.folderService.getFolder().id;
  }
}

<div *ngIf="notDeleted" class="todo-format todo-change-color">
  <div class="todo-format--center-vertically">
    <input type="checkbox" class="todo-input-format" [(ngModel)]="toDo.marked"
      (change)="updateToDo()"/>
    <label class="todo-label-format"> {{ toDo.title }} </label>
    <fa-icon
      (click)="deleteToDo()"
      [icon]="faTimesCircle"
      class="todo-erase-format"
      title="Delete ToDo"

    >
    </fa-icon>
    <a (click) = "setToDoInService()" [routerLink]="['/toDos/edit',toDo.id]">
      <fa-icon
        [icon]="faPen"
        class="todo-edit-format"
        title="Edit ToDo"
      ></fa-icon>
    </a>
    <br />
    <label class="todo-description-format"> {{ toDo.description }}</label>
  </div>
</div>

// FrontEndReactJS/src/Components/ToDoItem/ToDoItem.jsx
import { Link } from "react-router-dom";
import { useState } from "react";
import "./ToDoItem.scss";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPen, faTimesCircle } from "@fortawesome/free-solid-svg-icons";
import { updateToDoMark } from "../../Api/ToDoApi";

function ToDoItem(props) {
  const [toDo, setTodo] = useState(props.toDo);

  const handleMarkChange = (e) => {
    const target = e.target;
    const checked = target.checked;
    updateToDoMark(toDo.id, checked).then(
      (response) => {
        if (response.status === 200) setTodo({ ...toDo, marked: checked });
        if (response.status === 500)
          props.setErrorMessage("Error updating the mark");
      },
      () => props.setErrorMessage("Error updating the mark")
    );
  };

  const deleteItem = () => {
    props.deleteToDo(toDo.id);
  };

  if (toDo !== undefined)
    return (
      <div className="todo-format todo-change-color">
        <div className="todo-format--center-vertically">
          <input
            type="checkbox"
            id={toDo.id}
            checked={toDo.marked}
            className="todo-input-format"
            onChange={handleMarkChange}
          />
          <label className="todo-label-format">{toDo.title}</label>
          <FontAwesomeIcon
            icon={faTimesCircle}
            className="todo-erase-format"
            onClick={deleteItem}
            title="Delete ToDo"
          />
          <Link
            to={`/toDos/edit/${toDo.id}`}
            state={{ toDo: toDo, folderId: props.folderId }}
          >
            <FontAwesomeIcon
              icon={faPen}
              className="todo-edit-format"
              title="Edit ToDo"
            />
          </Link>
          <br />
          <label className="todo-description-format">{toDo.description}</label>
        </div>
      </div>
    );
  else return null;
}

export default ToDoItem;
