// FrontEndReactJS/src/Screens/Edit/Edit.jsx
import { useLocation, useNavigate, Navigate } from "react-router-dom";
import "./Edit.scss";
import { useState } from "react";
import { updateToDoInfo } from "../../Api/ToDoApi";
import {
  toDoDescriptionNotEmpty,
  toDoTitleNotEmpty,
} from "../../Utils/CheckToDos";

function Edit(props) {
  const navigate = useNavigate();
  const location = useLocation();
  const [errorMessage, setErrorMessage] = useState("");
  const [newToDoInfo, setNewToDoInfo] = useState(
    location.state !== null ? location.state.toDo : null
  );

  const handleChange = (e) => {
    const target = e.target;
    const value = target.value;
    if (value.length <= 255) {
      const name = target.name;

      setNewToDoInfo({
        ...newToDoInfo,
        [name]: value,
      });
    }
  };

  const updateToDo = () => {
    updateToDoInfo(
      newToDoInfo.id,
      newToDoInfo.title,
      newToDoInfo.description,
      newToDoInfo.marked,
      location.state.folderId
    ).then(
      (response) => {
        if (response.status === 200) navigate(-1);
        if (response.status === 500) setErrorMessage("Error editing the To-Do");
      },
      () => setErrorMessage("Error editing the To-Do")
    );
  };

  const handleToDoChange = (e) => {
    e.preventDefault();
    try {
      toDoTitleNotEmpty(newToDoInfo.title);
      toDoDescriptionNotEmpty(newToDoInfo.description);
      updateToDo();
    } catch (error) {
      setErrorMessage(error.message);
    }
  };

  if (location.state !== null)
    return (
      <div className="edit-format">
        <label className="title-format"> Edit To-Do</label> <br />
        <div className="edit-container">
          <label>Editing Task "{location.state.toDo.title}"</label>
          <form className="edit-container__form" onSubmit={handleToDoChange}>
            <input
              className="input-format"
              onChange={handleChange}
              name="title"
              value={newToDoInfo.title}
              placeholder="Insert the To-Do's new title"
            />
            <input
              className="input-format"
              onChange={handleChange}
              name="description"
              value={newToDoInfo.description}
              placeholder="Insert the To-Do's new description"
            />
            <div>
              <button type="submit" className="button-format edit__button">
                <label>Save</label>
              </button>
            </div>
          </form>
          <button
            onClick={() => navigate(-1)}
            className="button-format edit__button"
          >
            <label>Cancel</label>
          </button>
          <div className="error-message-container">
            <label className="error-message-label">{errorMessage}</label>
          </div>
        </div>
      </div>
    );
  else return <Navigate to={"/toDos"} replace />;
}

export default Edit;

// FrontEndAngular/src/app/Screens/edit/edit.component.ts
import { Component, OnInit } from '@angular/core';
import { FolderService } from 'src/app/config/folder.service';
import { ToDos } from 'src/app/config/interfaces';
import { Response } from 'src/app/config/interfaces';
import { ToDoApiService } from 'src/app/config/to-do-api.service';
import { ToDosService } from 'src/app/config/to-dos.service';
import { Location } from '@angular/common';

@Component({
  selector: 'app-edit',
  templateUrl: './edit.component.html',
  styleUrls: ['./edit.component.scss']
})
export class EditComponent implements OnInit {

  toDo: ToDos = {
    id: NaN, title: "", description: "", marked: false,
    updatedAt: "", createdAt: ""
  }
  errorMessage: String = "";
  folderId: Number = NaN;
  constructor(private toDoService: ToDosService,
    private folderService: FolderService,
    private toDoApiService: ToDoApiService,
    private location: Location) { }

  returnPreviousPage() {
    this.location.back()
  }
  updateToDo() {
    console.log(this.toDo);
    //It has to update the ToDo in the Service
    this.toDoApiService.updateToDo(this.toDo.id,
      this.toDo.title,
      this.toDo.description,
      this.toDo.marked,
      this.folderId).then((response) => {
        if (response.status === 200) this.returnPreviousPage()
        if (response.status === 500) this.errorMessage = "Error updating ToDo"
      },
        () => this.errorMessage = "Error updating ToDo"
      )
  }

  ngOnInit(): void {
    this.toDo = this.toDoService.getToDo();
    this.folderId = this.folderService.getFolder().id;
  }

}

<div class="edit-format">
    <label class="title-format"> Edit To-Do</label> <br />
    <div class="edit-container">
      <label>Editing Task "{{toDo.title}}"</label>
      <form class="edit-container__form" >
        <input
          class="input-format"
          name="title"
          [(ngModel)]="toDo.title"
          placeholder="Insert the To-Do's new title"
        />
        <input
          class="input-format"
          name="description"
          [(ngModel)]="toDo.description"
          placeholder="Insert the To-Do's new description"
        />
        <div>
          <button type="submit" class="button-format edit__button"
            (click)="updateToDo()">
            <label>Save</label>
          </button>
        </div>
      </form>
      <button (click)="returnPreviousPage()"
        class="button-format edit__button"
      >
        <label>Cancel</label>
      </button>
      <div class="error-message-container">
        <label class="error-message-label">{{errorMessage}}</label>
      </div>
    </div>
  </div>
