// FrontEndAngular/src/app/Components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { LoginService } from 'src/app/config/login.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  constructor(private loginService: LoginService,
    private router: Router) {
      this.loginService.isLoggedIn.subscribe(logged => this.changeLoggedIn(logged))
  }

  isLoggedIn: boolean = false;

  private changeLoggedIn(isLoggedIn: boolean): void {
    this.isLoggedIn = isLoggedIn;
  }

  logOut() {
    this.loginService.LogOut()
    this.router.navigate([""])
  }

  ngOnInit(): void {
    this.loginService.isLoggedIn.subscribe(logged => this.changeLoggedIn(logged))
  }

}

<div class="header-format">
  <a
    routerLink="/toDos"
    [routerLinkActiveOptions]="{ exact: true }"
    routerLinkActive="header-button--active"
    class="header-button"
  >
    <label class="header-button__label">To-Do List</label>
  </a>
  <a
    *ngIf="!isLoggedIn; else notLoggedIn"
    routerLink="/"
    [routerLinkActiveOptions]="{ exact: true }"
    routerLinkActive="header-button--active"
    class="header-button header-button--right"
  >
    <label class="header-button__label">Login</label>
  </a>
  <ng-template #notLoggedIn>
    <a
      routerLink="/logout"
      class="header-button header-button--right"
      (click)="logOut()"
    >
      <label class="header-button__label">Logout</label>
    </a>
  </ng-template>
</div>

// FrontEnd/src/Components/Header/Header.jsx
import { NavLink } from "react-router-dom";
import "./Header.scss";

function Header(props) {
  return (
    <>
      <div className="header-format">
        <NavLink to={`/toDos`} className="header-button">
          <label className="header-button__label">To-Do List</label>
        </NavLink>
        {!props.isLoggedIn && (
          <NavLink to={`/`} className="header-button header-button--right">
            <label className="header-button__label">Login</label>
          </NavLink>
        )}
        {props.isLoggedIn && (
          <NavLink
            to={"/logout"}
            onClick={props.logoutUser}
            className="header-button header-button--right"
          >
            <label className="header-button__label">Logout</label>
          </NavLink>
        )}
      </div>
    </>
  );
}

export default Header;
