// FrontEndReactJS/src/Screens/ToDos_List/ToDosList.jsx
import { useState, useEffect, useCallback } from "react";
import { Navigate, useLocation } from "react-router";
import { Link } from "react-router-dom";
import { getAllToDosFromFolder, addToDo, deleteToDo } from "../../Api/ToDoApi";
import ToDoItem from "../../Components/ToDoItem/ToDoItem";
import "./ToDosList.scss";

function ToDos_List(props) {
  const location = useLocation();
  const [errorMessage, setErrorMessage] = useState("");
  const [toDoList, setToDoList] = useState([]);
  const [newToDo, setNewToDo] = useState(
    location.state !== null
      ? {
          title: "",
          description: "",
          marked: false,
          folderId: location.state.folder.id,
        }
      : {}
  );

  const deleteToDoFromDatabase = (id) => {
    deleteToDo(id).then(
      () => setToDoList(toDoList.filter((toDo) => toDo.id !== id)),
      () => setErrorMessage("Error deleting the ToDo")
    );
  };

  const addNewToDoToDatabase = () => {
    addToDo(newToDo).then(
      (response) => setToDoList([...toDoList, response.data]),
      () => setErrorMessage("Error creating the To-Do")
    );
  };

  const getToDosFromDatabase = useCallback(async () => {
    if (location.state !== null) {
      await getAllToDosFromFolder(location.state.folder.id).then(
        (response) => setToDoList(response.data),
        () => setErrorMessage("Error retrieving the folders")
      );
    }
  }, [location.state]);

  const addNewToDoItem = (e) => {
    e.preventDefault();
    try {
      if (newToDo.title === "")
        throw new Error("The title field cannot be empty");
      if (newToDo.description === "")
        throw new Error("The description field cannot be empty");
      const indexWithSameTitle = toDoList
        .map((toDo) => toDo.title)
        .indexOf(newToDo.title);
      if (indexWithSameTitle !== -1)
        throw new Error("The is already a ToDo with that title");
      addNewToDoToDatabase();
      setErrorMessage("");
    } catch (error) {
      setErrorMessage(error.message);
    } finally {
      setNewToDo({
        ...newToDo,
        title: "",
        description: "",
        marked: false,
      });
    }
  };

  const handleChangeNewTodo = (e) => {
    const target = e.target;
    const value = target.value;
    if (value.length <= 255) {
      const name = target.name;

      setNewToDo({
        ...newToDo,
        [name]: value,
      });
    }
  };

  useEffect(() => {
    getToDosFromDatabase();
  }, [getToDosFromDatabase]);

  if (location.state !== null)
    return (
      <div className="todo-list-format">
        <label className="title-format">To-Do List</label>
        <div className="sub-title-container">
          <Link to={"/toDos"} style={{ textDecoration: "none" }}>
            <label className="sub-title-format sub-title-format--pointer">
              Folders
            </label>
          </Link>{" "}
          <label className="sub-title-format">
            -{">"} {location.state.folder.title}
          </label>
        </div>
        <div className="todo-list__items-container">
          {toDoList.map((toDo) => {
            return (
              <ToDoItem
                toDo={toDo}
                key={toDo.id}
                deleteToDo={deleteToDoFromDatabase}
                folderId={location.state.folder.id}
                setErrorMessage={setErrorMessage}
              ></ToDoItem>
            );
          })}
        </div>
        <div className="todo-list__buttons">
          <form onSubmit={addNewToDoItem} className="todo-list__add">
            <div>
              <input
                type="text"
                className="input-format"
                name="title"
                value={newToDo.title}
                onChange={handleChangeNewTodo}
                placeholder="Insert new ToDo's Title"
              />
              <input
                type="text"
                className="input-format"
                name="description"
                value={newToDo.description}
                onChange={handleChangeNewTodo}
                placeholder="Insert new ToDo's Description"
              />
            </div>
            <button
              type="submit"
              className="button-format todo-list__add__button"
            >
              <label>Add</label>
            </button>
          </form>
          <div className="error-message-container">
            <label className="error-message-label">{errorMessage}</label>
          </div>
        </div>
      </div>
    );
  else return <Navigate to={"/toDos"} replace />;
}

export default ToDos_List;

// FrontEndAngular/src/app/Screens/to-dos-list/to-dos-list.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FolderService } from 'src/app/config/folder.service';
import { ToDoApiService } from 'src/app/config/to-do-api.service';
import { Folder, ToDos, ToDoToAdd } from 'src/app/config/interfaces';
import { toDoAlreadyExists, toDoDescriptionNotEmpty, toDoTitleNotEmpty } from 'src/app/Utils/CheckToDos';

@Component({
  selector: 'app-to-dos-list',
  templateUrl: './to-dos-list.component.html',
  styleUrls: ['./to-dos-list.component.scss']
})
export class ToDosListComponent implements OnInit {

  constructor(private folderService: FolderService,
    private toDosApiService: ToDoApiService) { }

  errorMessage: String = "";
  folder: Folder = { id: NaN, title: "", createdAt: "", updatedAt: "" };
  toDos: ToDos[] = [];
  newToDo: ToDoToAdd = { title: "", description: "", folderId: NaN };

  getToDos() {
    try {
      this.toDosApiService.getToDosFromFolder(this.folder.id).then((response) => {
        if (response.status === 200) this.toDos = response.data;
        if (response.status === 500) this.errorMessage = "Error retrieving Folders"
      }, () => this.errorMessage = "Error retrieving Folders")
    } catch (error: any) {
      this.errorMessage = "Error retrieving ToDo"
    }
  }

  createToDos() {
    try {
      this.newToDo.title = this.newToDo.title.trim()
      this.newToDo.description = this.newToDo.description.trim()
      toDoTitleNotEmpty(this.newToDo.title)
      toDoDescriptionNotEmpty(this.newToDo.title)
      toDoAlreadyExists(this.newToDo.title, this.toDos)
      this.toDosApiService.createToDo(this.newToDo).then((response) => {
        if (response.status === 500) this.errorMessage = "Error creating ToDo"
        if (response.status === 201) this.toDos.push(response.data)
      }, () => this.errorMessage = "Error creating ToDo")
    }
    catch (error: any) {
      this.errorMessage = "Error creating ToDo"
    }
    finally {
      this.newToDo = { title: "", description: "", folderId: this.newToDo.folderId }
    }

  }

  ngOnInit(): void {
    try {
      this.folder = this.folderService.getFolder();
      this.getToDos()
      this.newToDo.folderId = this.folder.id
    } catch (error: any) {
      this.errorMessage = error;
    }
  }

}

<div class="todo-list-format">
  <label class="title-format">To-Do List</label>
  <div class="sub-title-container">
    <a routerLink="/toDos" class="sub-title-format sub-title-format--pointer">
      <label >
        Folders
      </label>
    </a>
    <label class="sub-title-format"> -> {{ folder.title }} </label>
  </div>
  <div class="todo-list__items-container">
    <app-to-do-item *ngFor="let toDo of toDos" [toDo]="toDo" [errorMessage]="errorMessage"></app-to-do-item>
  </div>
  <div class="todo-list__buttons">
    <form class="todo-list__add">
      <div>
        <input
          type="text"
          class="input-format"
          [(ngModel)] = "newToDo.title"
          name="title"
          placeholder="Insert new ToDo's Title"
        />
        <input
          type="text"
          class="input-format"
          [(ngModel)] = "newToDo.description"
          name="description"
          placeholder="Insert new ToDo's Description"
        />
      </div>
      <button type="submit" class="button-format todo-list__add__button"
        (click)="createToDos()">
        <label>Add</label>
      </button>
    </form>
    <div class="error-message-container">
      <label class="error-message-label">{{ errorMessage }}</label>
    </div>
  </div>
</div>
